# Generated by Django 5.0.6 on 2024-11-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('cirurgias', models.TextField(blank=True, null=True)),
                ('doenca', models.TextField(blank=True, null=True, verbose_name='doença')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('quexa_pricipal', models.TextField(blank=True, null=True)),
                ('quexa_secundaria', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fichas Médicas',
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('ficha_criada', models.DateTimeField(auto_now_add=True)),
                ('ficha_atualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('pressao_sislotica', models.PositiveIntegerField(verbose_name='Pressão Sislótica')),
                ('pressao_diastolica', models.PositiveIntegerField(verbose_name='Pressão Diastólica')),
                ('evolucao', models.TextField(verbose_name='Evolução')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='pacientes.fichamedica')),
            ],
            options={
                'verbose_name_plural': 'Evoluções',
            },
        ),
        migrations.CreateModel(
            name='EVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('eva', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evas', to='pacientes.fichamedica')),
            ],
            options={
                'verbose_name_plural': 'Evas',
            },
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='pacientes.pacientes'),
        ),
    ]
